---
title: "Corona Virus Report"
author:
- familyname: XXXX
  othernames: XXX
  address: Monash Universtidy
  email: awid0001@student.monash.edu
  correspondingauthor: true
  qualifications:  XXX
- familyname: XXXX
  othernames: Reports
  address: XXX
  qualifications: XXX
- familyname: Wang
  othernames: Hanchen
  address: Monash Universtidy
  email: hwan0143@student.monash.edu
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)

```



\section*{Country XX1 and YY1"}


\section*{Country XX2 and YY2}

\section*{Country Japan and South Korea}

```{r}
cases <- read_csv("data/worldwidecases.csv")
jk <- cases %>% 
  select(day, 
         month, 
         year, 
         cases, 
         deaths, 
         countriesAndTerritories) %>% 
  filter(countriesAndTerritories == c("Japan", "South_Korea"))
```

```{r Table, cache = TRUE}
japan <- jk %>% 
  filter(countriesAndTerritories == "Japan") %>% 
  group_by(month) %>% 
  summarise(jp_cases = sum(cases), jp_deaths = sum(deaths)) 

southkorea <- jk %>% 
  filter(countriesAndTerritories == "South_Korea", 
         !month == "12") %>%
  group_by(month) %>% 
  summarise(kr_cases = sum(cases), kr_deaths = sum(deaths)) 

Table <- left_join(japan, southkorea, 
                   by = "month")
knitr::kable(
Table, booktabs = TRUE,
  caption = 'Covid cases and deaths of Japan and South Korea on 2020')
```


Figute1  table1 with reference

paper reference



